
namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.ToDoNotes = new HashSet<ToDoNote>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int Label { get; set; }

        // The proprty is named as Note1 but it is actually Note content(auto generated by entity framework)
        public string Note1 { get; set; }

        // The proprty is named as Label1 but it is actually Label FK(auto generated by entity framework)
        public virtual Label Label1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToDoNote> ToDoNotes { get; set; }
    }
}
